<?php
/**
 * TL_ROOT/system/modules/uploaderjumploader/languages/de/tl_files.php 
 * 
 * Contao extension: uploaderjumploader 1.0.0 rc1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2013 Marko Cupic, Yannick Witschi 
 * License   : LGPL 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_files']['noJavaAlert'] = "Das Applet erfordert ein java Plug-in für den Betrieb. Bitte downloaden Sie das Java-Browser-Plugin oder aktivieren Sie dieses.";
 
?>
